default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pudzian

test:
  <<: *default
  database: test-pudzian

production:
  <<: *default
  database: pudzian
  username: postgresqluser
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
